version: '3'

services:
  app:
    image: jboss/keycloak:15.0.0
    env_file:
      - .env
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: ${DB_VENDOR}
    ports:
      - 8080:8080
